# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myproto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='myproto.proto',
  package='mypackage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmyproto.proto\x12\tmypackage\"\x14\n\x05\x46loat\x12\x0b\n\x03val\x18\x01 \x01(\x02\x32\xda\x01\n\tMyService\x12/\n\x07GetSqrt\x12\x10.mypackage.Float\x1a\x10.mypackage.Float\"\x00\x12\x32\n\x08GetSigma\x12\x10.mypackage.Float\x1a\x10.mypackage.Float\"\x00(\x01\x12\x34\n\nGetFactors\x12\x10.mypackage.Float\x1a\x10.mypackage.Float\"\x00\x30\x01\x12\x32\n\x06GetMax\x12\x10.mypackage.Float\x1a\x10.mypackage.Float\"\x00(\x01\x30\x01\x62\x06proto3'
)




_FLOAT = _descriptor.Descriptor(
  name='Float',
  full_name='mypackage.Float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='mypackage.Float.val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['Float'] = _FLOAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Float = _reflection.GeneratedProtocolMessageType('Float', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT,
  '__module__' : 'myproto_pb2'
  # @@protoc_insertion_point(class_scope:mypackage.Float)
  })
_sym_db.RegisterMessage(Float)



_MYSERVICE = _descriptor.ServiceDescriptor(
  name='MyService',
  full_name='mypackage.MyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=51,
  serialized_end=269,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSqrt',
    full_name='mypackage.MyService.GetSqrt',
    index=0,
    containing_service=None,
    input_type=_FLOAT,
    output_type=_FLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSigma',
    full_name='mypackage.MyService.GetSigma',
    index=1,
    containing_service=None,
    input_type=_FLOAT,
    output_type=_FLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFactors',
    full_name='mypackage.MyService.GetFactors',
    index=2,
    containing_service=None,
    input_type=_FLOAT,
    output_type=_FLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMax',
    full_name='mypackage.MyService.GetMax',
    index=3,
    containing_service=None,
    input_type=_FLOAT,
    output_type=_FLOAT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYSERVICE)

DESCRIPTOR.services_by_name['MyService'] = _MYSERVICE

# @@protoc_insertion_point(module_scope)
